### ISSUE TITLE
Schedule isn't  working

### ISSUE THREAD

**Issue by levend18** [suhaboncukcu/assign-task#1]
While i'm tring to send a schedule to missions Entity , my schedule is lost, but when i can sent a schedule2 to  a Entity without losing .
Thank for your free times :)

**Comment by suhaboncukcu** [comment]
I couldn't reproduce the issue. 

Could you show some examples of your database and the code you are using?

**Comment by levend18** [comment]
$this->loadModel('AssignTask.Missions');
  $mission = $this->Missions->newEntity()
this is my array 
$data [
  "to_id" => 21
  "from_id" => 21
  "mission" => "sadasd"
  "schedule" => "2016-11-9 00:00:00"
]
 $this->Missions->patchEntity($mission, $data);
 $this->Missions->save($mission);
Can we change schedule to missionDate ? i thing when we do that , that will going work fine

**Comment by suhaboncukcu** [comment]
can you try 09 instead of 9 ?

**Comment by levend18** [comment]
Sorry, not work

**Comment by suhaboncukcu** [comment]
on windows machines, schedule should be sent as time() object
